version: '2'
services:
  web:
    build: .
    working_dir: /code
    command: pserve development.ini --reload
    ports:
      - "6543:6543"
    volumes:
      - .:/code
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8000:8080"
    volumes:
      - ./api_docs/swagger.json:/api_docs/swagger.json
    environment:
      SWAGGER_JSON: /api_docs/swagger.json
